<?php
namespace Route;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Data
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'siteid',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'request_uri',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $siteid = null;
    /**
     * @var string
     */
    public $request_uri = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['siteid'])) {
                $this->siteid = $vals['siteid'];
            }
            if (isset($vals['request_uri'])) {
                $this->request_uri = $vals['request_uri'];
            }
        }
    }

    public function getName()
    {
        return 'Data';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->siteid);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->request_uri);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Data');
        if ($this->siteid !== null) {
            $xfer += $output->writeFieldBegin('siteid', TType::STRING, 1);
            $xfer += $output->writeString($this->siteid);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->request_uri !== null) {
            $xfer += $output->writeFieldBegin('request_uri', TType::STRING, 2);
            $xfer += $output->writeString($this->request_uri);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
